# This is a basic workflow to help you get started with Actions

name: eugeneermakov696

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  GITHUB_ACTIONS: hello_mates))

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  github-task-job:

    steps:

      - name: usage of variable
        run: echo "My message is I ${{ env.GITHUB_ACTIONS }}"

      - name: presantation of branch and repo names
        run: echo "Branch name is ${{ github.ref }}, repo name is ${{ github.repository }}"

      - name: event  
        run: echo "Trigger event is ${{ github.event_name }}"

    runs-on: ubuntu-latest
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
